rec_message = [
    {
        "channels": "private",
        "email_group": None,
        "for_email": False,
        "for_phone": False,
        "for_slack": False,
        "message": "Candidate name: @candidate_name: \n Candidate email: @candidate_email: \n Exam Token: @exam_token: \n Job Profile: @job_profile:",
        "message_color": None,
        "message_key": "exam_candidate_sign_up",
        "message_origin": "RECRUIT",
        "message_type": "simple_message",
        "sended_to": "public",
        "slack_channel": None,
        "working": True
    },
    {
        "channels": "private",
        "email_group": None,
        "for_email": False,
        "for_phone": False,
        "for_slack": False,
        "message": "Interview is Scheduled for !! Job Profile: @tag title: \n Candidate Name: @candidate_name: \n On Dated date At schedule time \n Cv: @link: ",
        "message_color": None,
        "message_key": "exam_candidate_email_process_if_tag_type_is_default",
        "message_origin": "RECRUIT",
        "message_type": "simple_message",
        "sended_to": "public",
        "slack_channel": None,
        "working": True
    },
    {
        
        "channels": "private",
        "email_group": None,
        "for_email": False,
        "for_phone": False,
        "for_slack": False,
        "message": "Job Profile: @tag_title \n Candidate Name: @candidatename: \n Tag Moved To: @tagetitle \n Assignee: @assignee_email On Dated @date: \n Candidate url: @candidate_url  ",
        "message_color": None,
        "message_key": "for_email_process_if_tag_type_is_other",
        "message_origin": "RECRUIT",
        "message_type": "simple_message",
        "sended_to": "public",
        "slack_channel": None,
        "working": True
    },
    {
        
        "channels": "private",
        "email_group": None,
        "for_email": False,
        "for_phone": False,
        "for_slack": False,
        "message": "A note has been added \n Candidate Name: @candidate_name: \n Assignee: @candidateemail: \n Note: @note: \n On Dated @date: \n Candidate url: @candidate_url: ",
        "message_color": None,
        "message_key": "for_inserting_note",
        "message_origin": "RECRUIT",
        "message_type": "simple_message",
        "sended_to": "public",
        "slack_channel": None,
        "working": True
    },
    {
        
        "channels": "private",
        "email_group": None,
        "for_email": False,
        "for_phone": False,
        "for_slack": False,
        "message": "<!here> *A candidate submitted the exam*  Email: @candidate_email:  Max Marks: @marks:  Marks scored: @score:  Group wise scores- @grp_score:  Candidate url: @candidate_url: ",
        "message_color": None,
        "message_key": "exam result",
        "message_origin": "RECRUIT",
        "message_type": "simple_message",
        "sended_to": "public",
        "slack_channel": None,
        "working": True
    },
    {
        
        "channels": "private",
        "email_group": None,
        "for_email": False,
        "for_phone": False,
        "for_slack": False,
        "message": "@email: is calling for help while giving test <!here> ``  @message: `` ",
        "message_color": None,
        "message_key": "ask for help",
        "message_origin": "RECRUIT",
        "message_type": "simple_message",
        "sended_to": "public",
        "slack_channel": None,
        "working": True
    },
    {
        
        "channels": "private",
        "email_group": None,
        "for_email": False,
        "for_phone": False,
        "for_slack": False,
        "message": "A new candidate  @email:  has applied for job .",
        "message_color": None,
        "message_key": "add candidate: if candidate already exist",
        "message_origin": "RECRUIT",
        "message_type": "simple_message",
        "sended_to": "public",
        "slack_channel": None,
        "working": True
    },
    {
        
        "channels": "private",
        "email_group": None,
        "for_email": False,
        "for_phone": False,
        "for_slack": False,
        "message": "A new candidate  @email: is in pending list for exam. Kindly approve.",
        "message_color": None,
        "message_key": "add candidate: if candidate is new",
        "message_origin": "RECRUIT",
        "message_type": "simple_message",
        "sended_to": "public",
        "slack_channel": None,
        "working": True
    },
    {
        
        "channels": "private",
        "email_group": None,
        "for_email": False,
        "for_phone": False,
        "for_slack": False,
        "message": "<!here> *reminder message, interview is scheduled for tommorow* \n Candidate name: @candidatename: \n Email: @candidate_email: \n Job profile: @jobprofile: \n Round: @round: \n At: @time: \n Candidate url: @candidate_url: ",
        "message_color": None,
        "message_key": "For reminder",
        "message_origin": "RECRUIT",
        "message_type": "simple_message",
        "sended_to": "public",
        "slack_channel": None,
        "working": True
    },
    {
        "channels": "private",
        "email_group": None,
        "for_email": False,
        "for_phone": False,
        "for_slack": False,
        "message": " <!here> A candidate just started his/her exam by exam link \n name: @name: \n email: @email: ",
        "message_color": None,
        "message_key": "candidate_exam_detail",
        "message_origin": "RECRUIT",
        "message_type": "simple_message",
        "sended_to": "public",
        "slack_channel": None,
        "working": True
    }
]