rec_templates = [
    {
    "Doc_type" : "email",
    "for" : "First Round",
    "message" : "Hi,#name: <br/> Your First round with #company: has been schedule on #date: at the #venue: for Javascript Developer <br/> #hr_signature: ",
    "message_key" : "first_round_for_javascript_developer",
    "message_origin" : "RECRUIT",
    "message_subject" : "#name!,your interview for First round of javascript developer is scheduled",
    "recruit_details" : "First Round For Javascript Developer",
    "version" : 1,
    "default" : True,
    "working" : True,
    "mobile_message" : "Hi,#name: <br/> Your First round with #company: has been schedule on #date: at the #venue: for Javascript Developer"
    },
    {
    "Doc_type" : "email",
    "for" : "Second Round",
    "message" : "Hi,#name: <br/> Your Second round with #company: has been schedule on #date: at the #venue: for Php developer <br/> #hr_signature: ",
    "message_key" : "second_round_for_php_developer",
    "message_origin" : "RECRUIT",
    "message_subject" : "#name!,your interview for Second round for Php developer is scheduled",
    "recruit_details" : "Second Round For Php Developer",
    "version" : 1,
    "default" : True,
    "working" : True,
    "mobile_message" : "Hi,#name: <br/> Your Second round with #company: has been schedule on #date: at the #venue: for Php developer"
    },   
    {
    "Doc_type" : "email",
    "for" : "Interviewee Reject",
    "message" : "<p>Dear Applicant <br/> Thank you very much for taking the time to interview with us for the profile of #Profile Name:. We regret to inform that you couldn't clear the subsequent rounds of the interview process but we do appreciate your interest in the company and the job.<br/>We wish you all the best for future endeavors <br/>Regards<br/> #hr_signature: </p>",
    "message_key" : "interviewee_reject",
    "message_origin" : "RECRUIT",
    "message_subject" : "interviewee Rejection",
    "recruit_details" : "Interviwee Reject",
    "version" : 1,
    "default" : True,
    "working" : True
    },
    {
    "Doc_type" : "email",
    "for" : "Interviwee Hold",
    "message" : "<p>Dear Applicant<br/>Hope you are doing good!<br/>This is to inform you that with respect your application and subsequent interview with #company: your candidature has been put on hold for a while due to unavoidable circumstance.<br/>We will surely get back to you once the position re-opens. Thank you so much for showing your pleasant interest with the company and the job.<br/>Regards<br/> #hr_signature: </p>",
    "message_key" : "interviewee_onhold",
    "message_origin" : "RECRUIT",
    "message_subject" : "interviewee put on hold",
    "recruit_details" : "Interviewee On Hold",
    "version" : 1,
    "default" : True,
    "working" : True
    },
    {
    "Doc_type" : "email",
    "for" : "Interviewe Selection",
    "message" : "<p>Dear #name: <br/> Greetings from Excellence Technologies! <br/>We are pleased to inform you that based on your subsequent interview and application; we are welcoming you to our organization Excellence Technologies for the position of #designation: We look forward to you joining us from #date: at #time:. <br/> Please do not hesitate to call us for any information you may need.<br/>Kindly send your acceptance for the same.<br/> Congratulations! <br/> With Regards,<br/> #hr_signature: </p>",
    "message_key" : "interviewee_selection",
    "message_origin" : "RECRUIT",
    "message_subject" : "interviewee selected",
    "recruit_details" : "Interviewee Selection",
    "version" : 1,
    "default" : True,
    "working" : True
    },
    {
    "Doc_type" : "email",
    "for" : "Third Round",
    "message" : "Hi,#name: <br/> Your Third round with #company: has been schedule on #date: at the #venue: for Php developer <br/> #hr_signature: ",
    "message_key" : "third_round_for_php_developer",
    "message_origin" : "RECRUIT",
    "message_subject" : "#name!,your interview for Third round for Php developer is scheduled ",
    "recruit_details" : "Third Round For Php Developer",
    "version" : 1,
    "default" : True,
    "working" : True,
    "mobile_message" : "Hi,#name: Your Third round with #company: has been schedule on #date: at the #venue: for Php developer"
    },
    {
    "Doc_type" : "email",
    "for" : "First Round",
    "message" : "Hi,#name: <br/> Your First round with #company: has been schedule on #date: at the #venue: for PHP Developer <br/> #hr_signature: ",
    "message_key" : "first_round_for_php_developer",
    "message_origin" : "RECRUIT",
    "message_subject" : "#name!,your interview for First round for Php developer is scheduled",
    "recruit_details" : "First Round For Php Developer",
    "version" : 1,
    "default" : True,
    "working" : True,
    "mobile_message" : "Hi,#name: Your First round with #company: has been schedule on #date: at the #venue: for PHP Developer"
    },
    {
    "Doc_type" : "email",
    "for" : "Second Round",
    "message" : "Hi,#name: <br/> Your Second round with #company: has been schedule on #date: at the #venue: for Javascript developer <br/> #hr_signature: ",
    "message_key" : "second_round_for_javascript_developer",
    "message_origin" : "RECRUIT",
    "message_subject" : "#name!,your interview for Second round for Javascript developer is scheduled",
    "recruit_details" : "Second Round For Javascript Developer",
    "version" : 1,
    "default" : True,
    "working" : True,
    "mobile_message" : "Hi,#name: Your Second round with #company: has been schedule on #date: at the #venue: for Javascript developer"
    },
    {
    "Doc_type" : "email",
    "for" : "Third Round",
    "message" : "Hi,#name: <br/> Your Third round with #company: has been schedule on #date: at the #venue: for Javascript developer <br/> #hr_signature: ",
    "message_key" : "third_round_for_javascript_developer",
    "message_origin" : "RECRUIT",
    "message_subject" : "#name!,your interview for Third round for Javascript developer is scheduled",
    "recruit_details" : "Thrid Round For Javascript Developer",
    "version" : 1,
    "default" : True,
    "working" : True,
    "mobile_message" : "Hi,#name: Your Third round with #company: has been schedule on #date: at the #venue: for Javascript developer"
    },
    {
    "Doc_type" : "email",
    "for" : "Password reset",
    "message" : "<p>Dear #name:, <br/> Your password is reset below is the new password <br/> #password: </p> ",
    "message_key" : "Password reset",
    "message_origin" : "RECRUIT",
    "message_subject" : "#name: your password is reset",
    "recruit_details" : "Password reset",
    "version" : 1,
    "default" : True,
    "working" : True
    },
    {
    "Doc_type" : "email",
    "for" : "Interview Reminder",
    "message" : "<p>Dear Applicant<br/>Hope you are doing good!<br/>This is to inform you that your interview with #company: is schdule for #interview_date:<br/>Regards<br/> #hr_signature: </p>",
    "message_key" : "Interview Reminder",
    "message_origin" : "RECRUIT",
    "message_subject" : "interview reminder",
    "recruit_details" : "Interview Reminder",
    "version" : 1,
    "working" : True,
    "default" : False,
    "mobile_message" : "Hi #name: This is to inform you that your interview with #company: is schedule for #interview_date: on #venue:"
    },
    {
    "message_key" : "chat_interested",
    "message" : "<p>\n  Hi #name: if you are interested for this Job offer from #company: <br/> <br/> Please kindly reply to this mail and we will contact you on this same email for further details.<br/>#hr_signature:\n</p>",
    "working" : True,
    "message_origin" : "RECRUIT",
    "message_subject" : "confirmation from #company:",
    "version" : 1,
    "default" : True,
    "for" : "chat",
    "recruit_details" : "still interested",
    "Doc_type" : "email"
    },
    {
    "message_key" : "chat_details",
    "message" : "<p>\n  Hi #name: if you are interested for this Job offer from #company: <br/> <br/> Please kindly reply to this email we would love to have a chat with you \n.<br/>#hr_signature:\n</p>",
    "working" : True,
    "message_origin" : "RECRUIT",
    "message_subject" : "confirmation from #company:",
    "version" : 1,
    "default" : False,
    "for" : "chat",
    "recruit_details" : "we would love to have a chat with you",
    "Doc_type" : "email"
    }
]